# Generated by Django 4.2.7 on 2023-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.CharField(max_length=200)),
                ('Content', models.TextField(max_length=10000)),
                ('Reporter', models.CharField(max_length=200)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='News_image')),
                ('date_reported', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
